### ISSUE TITLE
panic: Invalid line format

### ISSUE THREAD

**Issue by arsham** [schrej/godacov#4]
Hi,
I just started using codacy for [this](https://github.com/arsham/expipe) project and I've encountered a panic. Travis reports the following:
```
panic: Invalid line format
goroutine 1 [running]:
github.com/schrej/godacov/cmd.run(0x958180, 0xc42012a180, 0x0, 0x6)
	/home/travis/gopath/src/github.com/schrej/godacov/cmd/root.go:81 +0x615
github.com/spf13/cobra.(*Command).execute(0x958180, 0xc4200a8010, 0x6, 0x6, 0x958180, 0xc4200a8010)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x958180, 0x6c7294, 0xc420136200, 0x95bd50)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x958180, 0xc42007c058, 0x0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/schrej/godacov/cmd.Execute()
	/home/travis/gopath/src/github.com/schrej/godacov/cmd/root.go:49 +0x2d
main.main()
	/home/travis/gopath/src/github.com/schrej/godacov/main.go:19 +0x20
```
Here is my coverage script:
```bash
#!/usr/bin/env bash

set -e
echo "" > coverage.txt

for d in $(go list ./... | grep -v vendor); do
    go test -coverprofile=profile.out -covermode=atomic $d
    if [ -f profile.out ]; then
        cat profile.out >> coverage.txt
        rm profile.out
    fi
done
```
This is my travis configuration:
```yaml
sudo: required

language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/schrej/godacov

script:
  - glide install
  - ./configs/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - godacov -t $CODACY_PROJECT_TOKEN -r ./coverage.txt -c $TRAVIS_COMMIT
```
